services:
  fastapi:
    build:
      dockerfile: /backend/Dockerfile
    container_name: fastapi_container
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
