services:
    fastapi:
        build:
            dockerfile: ./backend/Dockerfile
        container_name: fastapi_container
        ports:
            - 8000:8000
        depends_on:
            - mongodb
        environment:
            - DB_HOST=mongodb
            - ENV=prod

    next:
        build:
            dockerfile: ./frontend/Dockerfile
        container_name: nextjs_container
        ports:
            - 3000:3000
        depends_on:
            - fastapi
        environment:
            - VITE_API_URL=http://localhost:8000

    mongodb:
        image: mongo:latest
        container_name: mongodb_container
        ports:
            - "27017:27017"
