name: Tests
on:
    pull_request:
        branches:
            - master

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pavelzw/pytest-action@v2
            - run: pip install ruff
            - run: ruff check .
