name: Run Python tests

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Run tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]

        steps:
            - uses: szenius/set-timezone@v1.2
              with:
                  timezoneLinux: "Europe/Berlin"
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  pip install fastapi black ruff pydantic pymongo asyncio aiohttp motor pandas pytest pytest-asyncio
            - name: Run tests
              run: pytest
              working-directory: ./backend
